### ISSUE TITLE
Worked once and then stopped

### ISSUE THREAD

**Issue by kalzEOS** [DenysMb/KDE-DynamicThemeGenerator#1]
Script worked once then stopped working. That one time it worked, the wallpaper is gone. Not sure what troubleshooting I can do, but just wanted to report it here.
Thanks

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.2-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Dell Inc.
Product Name: Inspiron 7573

**Comment by DenysMb** [comment]
Thank you for open the issue. I will take a look.

**Comment by kalzEOS** [comment]
Ok, so I looked through the path where this script pushes the wallpapers, and they are there. It did create them, but they are just not showing in the kde wallpaper chooser for some reason 
![Screenshot_20221019_162205](https://user-images.githubusercontent.com/49320606/196796237-ba018f9f-3c3d-49cf-87be-ab72d5e8d2b7.png)

**Comment by DenysMb** [comment]
Can you show me the name of both of them (with the extension) and the metadata.desktop content?

**Comment by kalzEOS** [comment]
Ok, so I think I have figured it out. I've found a "content" folder and two other files "moedark.colors" and "desktop.metadata" in` /home/kalzi/.local/share/wallpapers/`. It is as if a folder/a theme or something got extracted in that directory. Removed those and now the script works just fine. I don't know where those three came from. I just thought that they looked out of place and removed them. Weird how they stopped the script from working
![22222](https://user-images.githubusercontent.com/49320606/196799504-bc3bbc0d-0116-4cb7-9f4d-dff057ee0605.png)

Content folder has two images folders and they are all empty
 
metadata.desktop has this in it:
```

[Desktop Entry]
Name=
[Desktop Entry]
Name=
```

modedark.colors has this:

```
[ColorEffects:Disabled]
Color=112,111,110
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=0

[ColorEffects:Inactive]
ChangeSelectionColor=false
Color=112,111,110
ColorAmount=-0.9500000000000001
ColorEffect=0
ContrastAmount=0.1
ContrastEffect=2
Enable=true
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=241,104,111
BackgroundNormal=47,52,58
DecorationFocus=63,69,77
DecorationHover=255,99,118
ForegroundActive=255,128,224
ForegroundInactive=160,160,160
ForegroundLink=46,184,230
ForegroundNegative=240,1,1
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=255,102,102

[Colors:Complementary]
BackgroundAlternate=38,41,46
BackgroundNormal=38,41,46

[Colors:Selection]
BackgroundAlternate=255,99,118
BackgroundNormal=255,99,118
DecorationFocus=63,69,77
DecorationHover=255,99,118
ForegroundActive=255,128,224
ForegroundInactive=160,160,160
ForegroundLink=46,184,230
ForegroundNegative=240,1,1
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=255,102,102

[Colors:Tooltip]
BackgroundAlternate=46,50,56
BackgroundNormal=46,50,56
DecorationFocus=63,69,77
DecorationHover=255,99,118
ForegroundActive=255,128,224
ForegroundInactive=225,225,225
ForegroundLink=46,184,230
ForegroundNegative=240,1,1
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=255,102,102

[Colors:View]
BackgroundAlternate=38,41,46
BackgroundNormal=38,41,46
DecorationFocus=63,69,77
DecorationHover=255,99,118
ForegroundActive=255,128,224
ForegroundInactive=160,160,160
ForegroundLink=46,184,230
ForegroundNegative=240,1,1
ForegroundNeutral=255,221,0
ForegroundNormal=254,254,254
ForegroundPositive=128,255,128
ForegroundVisited=255,102,102

[Colors:Window]
BackgroundAlternate=38,41,46
BackgroundNormal=38,41,46
DecorationFocus=63,69,77
DecorationHover=255,99,118
ForegroundActive=255,128,224
ForegroundInactive=160,160,160
ForegroundLink=46,184,230
ForegroundNegative=240,1,1
ForegroundNeutral=255,221,0
ForegroundNormal=255,255,255
ForegroundPositive=128,255,128
ForegroundVisited=255,102,102

[General]
ColorScheme=MoeDark
Name=MoeDark
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground=38,41,46
activeBlend=38,41,46
activeForeground=255,255,255
inactiveBackground=38,41,46
inactiveBlend=38,41,46
inactiveForeground=150,150,150


```

**Comment by DenysMb** [comment]
This color scheme doesn't have nothing to do with this script, but this metadata.desktop have.
The problem here is because, or you generate a wallpaper without name, or itself, for some reason, is not accepting the name that you are writing. 
Anyway, I will update the code to not accept empty names. I will also try to do another change, to avoid to use a name that was already used or to replace it if you use the same name.

**Comment by DenysMb** [comment]
I just updated the script and now it shouldn't happen anymore. 🙂
